# Generated by Django 3.1.1 on 2022-01-14 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link_Name', models.CharField(max_length=255, verbose_name='Link Name')),
                ('Link_HTTP', models.URLField(max_length=255, verbose_name='URL')),
                ('Link_Icon', models.CharField(help_text='<strong>Font Awesome Code</strong><br/>', max_length=255, verbose_name='Icon Image')),
            ],
            options={
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Full_Name', models.CharField(blank=True, default='first last', max_length=255, null=True, verbose_name='Name')),
                ('User_Image', models.ImageField(blank=True, upload_to='images/', verbose_name='Profile Image')),
                ('User_Title', models.CharField(max_length=255, verbose_name='Header')),
                ('User_Summary', models.CharField(max_length=255, verbose_name='Summary')),
                ('User_Phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('User_Email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('User_Links', models.ManyToManyField(to='Profile.Links')),
                ('User_Profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
